### ISSUE TITLE
As a user, I want to create a "create an account" page. (13 Points)

### ISSUE THREAD

**Issue by SamHall5** [calebf2/EvacAssistant5.30#13]

**Comment by SamHall5** [comment]
Provide a username and password.
Make sure username is not already in database.

**Comment by calebf2** [comment]
Marked duplicate. There is a user story for this already, however the function between these stories is different. Thus, we want a label to show it is a duplicate, but also an enhancement.

**Comment by calebf2** [comment]
Set to 4 points as an arbitrary value. Should not be too difficult.
